#!/usr/bin/env bash

#
# Ssh into given node with authentication and replace all strings
# matching fromstr with tostr
#
cl=${1}      ; shift
host=${1}    ; shift
fromstr=${1} ; shift
tostr=${1}   ; shift
file=${1}

mj-ssh ${cl} ${host} 'sudo sed -i "s/${fromstr}/${tostr}/" ${file}' &
