#!/usr/bin/env bash

cl=${1} ; shift
cmd=${@}

if [ "$cl" == "" ] ; then echo -e "Usage: $0 clustername command\n\n\texample: $0 gibbon sudo service chef-client restart\n" ; exit ; fi

mjuserdir=/tmp/mj-${USER}
mjhosts=${mjuserdir}/${cl}-hosts.log

if [ ! -e "$mjhosts" ] ; then echo "Please run mj-cl-list to generate hosts first." ; exit ; fi

# iterate through list of nodes
for host in `cat ${mjhosts}`; do
    echo -e ${host}"\t"`mj-ssh ${cl} ${host} ${cmd}`
done
