#!/usr/bin/env bash

#
# Administer every hadoop daemon on cluster
#
cl=${1}     ; shift
daemon=${1} ; shift
action=${1}

if [ "$cl" == "" ] ; then echo -e "Usage: $0 clustername daemon_type action\n\n\texample: $0 gibbon datanode status\n" ; exit ; fi

exec mj-each ${cl} sudo service hadoop-0.20-${daemon} ${action}
